[workspace]
members = [
    "typst-bake",
    "typst-bake-macros",
    "examples/basic",
    "examples/with-inputs",
    "examples/with-package",
    "examples/with-files",
    "examples/quick-start",
]
resolver = "2"
