[package]
name = "example-basic"
version = "0.1.0"
edition = "2021"

[package.metadata.typst-bake]
template-dir = "./templates"
fonts-dir = "./fonts"

[dependencies]
typst-bake = { path = "../../typst-bake" }
include_dir = "0.7"
